added Doi Inthanon
OozyGrub/thai-national-park pull request #9
Opened 2022-10-05 08:06 UTC by burmanp

May add more later if this gets approved and merged okay.

2022-10-05 13:05 UTC, OozyGrub commented
I'll merge for sure only if issue #7 is completed.

2022-10-05 13:40 UTC, burmanp commented
> 

Okay np. I'll add the rest of it after work.

2022-10-06 03:28 UTC, OozyGrub requested changes

2022-10-06 03:28 UTC, OozyGrub commented on data.json
> +        "region": "Thai highlands",
```suggestion
        "region": "North",
```

2022-10-06 03:28 UTC, OozyGrub commented on data.json
> +      "nameTH": "ตำบล แม่ปืม",
```suggestion
      "nameTH": "อุทยานแห่งชาติแม่ปืม",
```

2022-10-06 03:28 UTC, OozyGrub commented on data.json
> +        "region": "Thai highlands",
Please change all `Thai highlands` to `North`

2022-10-07 00:42 UTC, OozyGrub commented
@burmanp Thanks for your hard work

2022-10-07 00:42 UTC, merged